[build]
# Onde o site compilado vai ficar (padrão é 'dist')
dist = "dist"
# O caminho base da URL. Se for rodar em localhost, é "/".
public_url = "/"

[serve]
# Porta do servidor (padrão 8080). Mude se tiver conflito.
port = 8080
# Abrir o navegador automaticamente?
open = false

[[assets]]
source = "public"
