[build]
target = "index.html"
dist = "dist"
public_url = "/"

[serve]
# MUDANÇA 1: Frontend roda na 3000 para não brigar com o Backend na 8080
port = 3000
open = true

[[assets]]
source = "public"

[[proxy]]
rewrite = "/buraco"
backend = "ws://127.0.0.1:8080/buraco"
ws = true
