[package]
name = "buracao_core"
version = "0.1.0"
edition = "2021"

[dependencies]
# Serde é o padrão para serialização (Rust -> JSON)
serde = { version = "1.0", features = ["derive"] }
rand = "0.9.2"
